SELECT *
FROM FOOD_DELIVERY

SELECT*
FROM FULFILMENT_CENTER

SELECT*
FROM MEAL_INFO

--GENERATE WEEKLY PERFOMANCE ANALYSIS
SELECT week, COUNT(num_orders)AS TOTAL_ORDERS,
        SUM(checkout_price) AS TOTAL_SALES,
		AVG(checkout_price) AS AVG_SALES
FROM FOOD_DELIVERY
GROUP BY week
ORDER BY week

--Center-Wise Analysis
SELECT center_id, COUNT(num_orders)AS TOTAL_ORDERS,
        SUM(checkout_price) AS TOTAL_SALES,
		AVG(checkout_price) AS AVG_SALES
FROM FOOD_DELIVERY
GROUP BY center_id
ORDER BY center_id

--Meal-Analysis (Most Ordered Meal Categories)
SELECT category ,COUNT(num_orders) AS TOTAL_ORDERS
FROM FOOD_DELIVERY FD
JOIN MEAL_INFO ML
ON FD.meal_id= ML.meal_id
GROUP BY category
ORDER BY TOTAL_ORDERS

--PROMOTION ANALYSIS(IMPACT OF EMAILER PROMOTION ON SALES)
SELECT emailer_for_promotion, SUM(checkout_price) AS TOTAL_SALES
FROM FOOD_DELIVERY
GROUP BY emailer_for_promotion

--PRICE ANALYSIS(AVERAGE BASE PRICE OF MEALS
SELECT AVG(base_price) AS AVG_BASE_PRICE
FROM FOOD_DELIVERY

--GEOGRAPHICAL ANALYSIS
SELECT FC.city_code, COUNT(num_orders) AS TOTAL_ORDERS
FROM FOOD_DELIVERY FD
JOIN FULFILMENT_CENTER FC
ON FD.center_id=FC.center_id
GROUP BY FC.city_code

--TREND ANALYSIS(TREND OF ORDERS & SALES OVER TIME)
SELECT week, COUNT(num_orders) AS TOTAL_ORDERS,
SUM(checkout_price) AS TOTAL_SALES
FROM FOOD_DELIVERY
GROUP BY week
ORDER BY week

--Operational Efficiency (AVERAGE OPERATIONAL AREA PER ORDER)
SELECT AVG(op_area) AS AVG_OP_AREA
FROM FULFILMENT_CENTER FC
JOIN FOOD_DELIVERY FD
ON FC.center_id=FD.center_id

--CUSTOMER BEHAVIOR ANALYSIS (REPEAT ORDER ANALYSIS)
SELECT id, COUNT(num_orders) AS TOTAL_ORDERS, COUNT(DISTINCT week) AS TOTAL_WEEKS_ORDERED, COUNT (num_orders)/COUNT(DISTINCT week) AS AVG_ORDERS_PER_WEEK
FROM FOOD_DELIVERY 
GROUP BY id
HAVING COUNT(num_orders)>1 --FILTER FOR CUSTOMERS WITH MORE THAN ONE ORDER

--CROSS TABLE ANALYSIS(CORRELATION BETWEEN MEAL CATEGORIES & CENTER TYPES)
SELECT ML.category,FC.center_type,COUNT(FD.num_orders) AS TOTAL_ORDERS 
FROM FOOD_DELIVERY FD
JOIN MEAL_INFO ML 
ON ML.meal_id=FD.meal_id
JOIN FULFILMENT_CENTER FC
ON FD.center_id=FC.center_id
GROUP BY ML.category,FC.center_type

--RELATIONSHIP ANALYSIS (IMPACT OF CENTER TYPE ON AVERAGE ORDER VALUE)
SELECT FC.center_type,AVG(FD.checkout_price) AS AVG_ORDER_VALUE
FROM FOOD_DELIVERY FD
JOIN FULFILMENT_CENTER FC
ON FD.center_id =FC.center_id
GROUP BY FC.center_type

--TOP PERFOMING FULFILMENT CENTERS
SELECT center_id,COUNT (num_orders) AS TOTAL_ORDERS,SUM(checkout_price) AS TOTAL_SALES
FROM FOOD_DELIVERY
GROUP BY center_id
ORDER BY TOTAL_SALES DESC

--CUISINE ANALYSIS (MOST POPULAR CUISINES)
SELECT cuisine,COUNT(num_orders) AS TOTAL_ORDERS
FROM FOOD_DELIVERY FD
JOIN MEAL_INFO ML
ON ML.meal_id=FD.meal_id
GROUP BY cuisine
ORDER BY TOTAL_ORDERS DESC

--CUSTOMER SEGMENTATION (HIGH VALUE CUSTOMERS)
SELECT id,SUM(checkout_price) AS TOTAL_SPENT
FROM FOOD_DELIVERY
GROUP BY id
HAVING SUM(checkout_price)>200 --FILTER FOR CUSTOMERS WHO SPENT MORE THAN 200

--AVERAGE ORDER VALUE BY MEAL CATEGORY
SELECT ML.category,AVG(FD.checkout_price) AS AVG_ORDER_VALUE
FROM FOOD_DELIVERY FD
JOIN MEAL_INFO ML
ON ML.meal_id=FD.meal_id
GROUP BY ML.category

--INACTIVE FULFILMENT CENTERS
SELECT FC.center_id,COUNT(FD.num_orders) AS TOTAL_ORDERS
FROM FULFILMENT_CENTER FC
LEFT JOIN FOOD_DELIVERY FD
ON FC.center_id =FD.center_id
GROUP BY FC.center_id
HAVING COUNT(FD.num_orders)=0

--TOP CUSTOMERS BY TOTAL ORDERS
SELECT id,COUNT(num_orders) AS TOTAL_ORDERS
FROM FOOD_DELIVERY
GROUP BY id
ORDER BY TOTAL_ORDERS DESC

--SALES DISTRIBUTION BY CENTER TYPE AND CITY
SELECT FC.center_type,FC.city_code,SUM(FD.checkout_price) AS TOTAL_SALES
FROM FULFILMENT_CENTER FC
JOIN FOOD_DELIVERY FD
ON FC.center_id=FD.center_id
GROUP BY FC.center_type,FC.city_code

--MEAL CATEGORIES WITH HIGHEST AND LOWEST AVERAGE PRICES
SELECT ML.category,MAX(checkout_price)AS MAX_PRICE,MIN(checkout_price) AS MIN_PRICE
FROM FOOD_DELIVERY FD
JOIN MEAL_INFO ML 
ON FD.meal_id=ML.meal_id
GROUP BY ML.category
