SELECT*
FROM SMART_PHONE

--SUMMARY STATISTICS
SELECT
  AVG(price) AS AVGPRICE,
  MAX(price) AS MAXPRICE,
  MIN(price) AS MINPRICE,
  AVG(rating) AS AVGRATING,
  MAX(rating) AS MAXRATING,
  MIN(rating) AS MINRATING
FROM SMART_PHONE

--BRAND ANALYSIS
SELECT 
  brand_name,
  COUNT(*) AS total_phones,
  AVG(price) AS AVGPRICE,
  AVG(rating) AS AVGRATING
FROM SMART_PHONE
GROUP BY brand_name
ORDER BY AVGPRICE DESC

--COUNT OF PHONES WITH SPECIFIC FEATURES
SELECT
   COUNT(*) AS TOTAL_5G
FROM SMART_PHONE
WHERE has_5g = has_5g

SELECT
   COUNT(*) AS TOTAL_NFC
FROM SMART_PHONE
WHERE has_nfc = has_nfc

--TOP MOST EXPENSIVE PHONES
SELECT 
  brand_name,
  model,
  price
FROM SMART_PHONE
ORDER BY price DESC

--PHONE WITH PRICE ABOVE AVERAGE
SELECT
 brand_name,
  model,
  price
FROM SMART_PHONE
WHERE price > (SELECT AVG(price) FROM SMART_PHONE)
ORDER BY price DESC

--AVERAGE PRICE AND RATING BY FEATURE
SELECT 
  has_5g,
  AVG(price) AS AVG_PRICE,
  AVG(rating) AS AVGRATING
FROM SMART_PHONE
GROUP BY has_5g

SELECT 
   has_nfc,
   AVG(price) AS AVG_PRICE,
   AVG(rating) AS AVGRATING
FROM SMART_PHONE
GROUP BY has_nfc
  
--PRICE DISTRIBUTION BY BRAND
SELECT
 brand_name,
 COUNT(*) AS TOTAL_PHONES,
 AVG(price) AS AVGPRICE,
 STDEV(price)AS STDDEV_PRICE
FROM SMART_PHONE
GROUP BY brand_name
ORDER BY AVGPRICE DESC

--RATING DISTRIBUTION BY BRAND
SELECT
 brand_name,
 COUNT(*) AS TOTAL_PHONES,
 AVG(price) AS AVGPRICE,
 STDEV(rating)AS STDDEV_RATING
FROM SMART_PHONE
GROUP BY brand_name
ORDER BY AVGPRICE DESC

--PHONES WITH SPECIFIC PRICE RANGE AND FEATURES
SELECT 
 brand_name,
 model,
 price,
 rating
FROM SMART_PHONE
WHERE price BETWEEN 30000 AND 55000
AND has_5g=has_5g

SELECT 
 brand_name,
 model,
 price,
 rating
FROM SMART_PHONE
WHERE price BETWEEN 30000 AND 55000
AND has_nfc=has_nfc

--TOP RATED PHONES BY BRAND
SELECT
 brand_name,
 model,
 price,
 rating
FROM SMART_PHONE
WHERE rating=(SELECT MAX(rating)AS MAXRATING FROM SMART_PHONE)
ORDER BY brand_name,model

----SUBQUERIES AND JOINS
--SUBQUERY FOR AVERAGE PRICE
SELECT 
 brand_name,
 model,
 price
FROM SMART_PHONE
WHERE price>(SELECT AVG(price) AS AVGPRICE FROM SMART_PHONE)
ORDER BY price DESC

--RANKING
SELECT 
  brand_name,
  model,
  price,
  RANK() OVER(ORDER BY price DESC) AS PRICE_RANK
FROM SMART_PHONE



