SELECT*
FROM KENYA_POPULATION_DIS

--Total Population by County
SELECT County, SUM(Total) AS TOTAL_POPULATION
FROM KENYA_POPULATION_DIS
GROUP BY County 
ORDER BY TOTAL_POPULATION DESC

--Total Male Population by County
SELECT County,SUM(Male) AS TOTAL_MALE
FROM KENYA_POPULATION_DIS
GROUP BY County
ORDER BY TOTAL_MALE DESC

--Total Female Population by County
SELECT County,SUM(Female) AS TOTAL_FEMALE
FROM KENYA_POPULATION_DIS
GROUP BY County
ORDER BY TOTAL_FEMALE DESC

--Total Intersex Population by County
SELECT County, SUM(Intersex) AS TOTAL_INTERSEX
FROM KENYA_POPULATION_DIS
GROUP BY County
ORDER BY TOTAL_INTERSEX DESC

--OVERALL POPULATION SUMMARY
SELECT County,
 SUM(Total) AS TOTAL_POPULATION,
 SUM(Female) AS TOTAL_FEMALE,
 SUM(Male) AS TOTAL_MALE,
SUM(Intersex) AS TOTAL_INTERSEX
FROM KENYA_POPULATION_DIS
GROUP BY County

--PERCENTAGE DISTRIBUTION OF GENDERS PER COUNTY
SELECT County,
 SUM(Female)/ SUM(Total) *100 AS FEMALE_PERCENTAGE,
 SUM(Male) /SUM(Total) *100 AS MALE_PERCENTAGE,
SUM(Intersex) /SUM(Total) *100 AS INTERSEX_PERCENTAGE
FROM KENYA_POPULATION_DIS
GROUP BY County

--COUNTY WITH THE HIGHEST TOTAL POPULATION
SELECT County
FROM KENYA_POPULATION_DIS
WHERE Total=(SELECT MAX(Total) AS TOTAL_MAX FROM KENYA_POPULATION_DIS)

--AVERAGE POPULATION BY COUNTY
SELECT County,AVG(Total) AS AVGPOP
FROM KENYA_POPULATION_DIS
GROUP BY County

--COUNT OF COUNTIES
SELECT COUNT(DISTINCT County) AS COUNTY_COUNT
FROM KENYA_POPULATION_DIS

--COUNTY WITH THE LOWEST TOTAL_POPULATION
SELECT County
FROM KENYA_POPULATION_DIS
WHERE Total=(SELECT MIN(Total) FROM KENYA_POPULATION_DIS)

--RATIO OF MALE TO FEMALE POPULATION IN EACH COUNTY
SELECT County,SUM(Male)/SUM(Female)*1.0 AS MALE_TO_FEMALE_RATIO
FROM KENYA_POPULATION_DIS
GROUP BY County

--PERCENTAGE CHANGE OF POPULATION OVER TIME
SELECT County,(MAX(Total)-MIN(Total)*100/MIN(Total)) AS POP_CHANGE
FROM KENYA_POPULATION_DIS
GROUP BY County

--COUNTY WITH THE LARGEST GENDER DISPARITY (Difference between Male and Female Population)
SELECT County
FROM KENYA_POPULATION_DIS
ORDER BY ABS(Male-Female) DESC

--COUNT OF COUNTIES WITH AN EQUAL NUMBER OF MALE AND FEMALE
SELECT COUNT(*) AS EQUAL_GENDER
FROM(SELECT County FROM KENYA_POPULATION_DIS GROUP BY County HAVING SUM(Male)=SUM(Female)) AS COUNTIES_EQUAL_GENDER

--COUNT OF COUNTIES WITH A MAJORITY OF MALES OR FEMALES
SELECT 
    CASE 
	   WHEN SUM(Male)> SUM(Female) THEN 'Male_Majority'
	   WHEN SUM(Female) >SUM(Male) THEN 'Female_Majority'
	   ELSE 'Equal'
	END AS MAJORITY_GENDER,
	COUNT (*) AS COUNTY_COUNT
	FROM KENYA_POPULATION_DIS
	

--COUNTY WITH THE HIGHEST GENDER RATIO
SELECT County
FROM KENYA_POPULATION_DIS
ORDER BY (Male*1.0/NULLIF(Female,0))DESC